name: Coordinator
version: '${version}'
main: com.earthpol.coordinator.Main
api-version: 1.16
folia-supported: true
authors: [ 0xBit ]
description: Converts real world decimal degree coordinates to ingame coordinates and vice versa
website: https://earthpol.github.com
commands:
  coordinate:
    description: Returns coordinates in game from real world coordinates
  getlocation:
    description: Returns real world coordinates relative to their ingame location
    alias: getloc
  coordinator:
    description: Base command for Coordinator